### PR TITLE
[UPDATE] Enhancements to CMU 15-445: Incorporating Latest Spring 2023 Content & Relevant Resource and Improved Overall Formatting

### PR DESCRIPTION
**Pull request by xzhseh**
This PR mainly does three things in general:
1. Introduces key enhancements to the `CMU 15-445` database systems course content, focusing on updating and expanding the material to include the most recent Spring 2023 version.
2. In line with the course's continual evolution, I have incorporated new and fresh resources to ensure the content remains current and comprehensive.
3. I have also made improvements to the overall formatting of the contents.

### CODE REVIEW

**Comment by xzhseh** [comment]
Same as before, if the updates to the Chinese version looks good, I'll proceed with updating the English version as well. :)

**Comment by PKUFlyingPig** [comment]
LGTM :)

**Comment by xzhseh** [comment]
I've made updates to the English version, resolved some inconsistencies in formatting, and further refined the overall structure to improve readability🥳

**Comment by PKUFlyingPig** [comment]
Appreciate your contribution :)

**Pull request merged**
