### PR TITLE
[README] Add links and README for English users

### PR DESCRIPTION
**Pull request by zxtanzxzx**
Add english descriptions and links to english version of ebook and english translation issue.

### CODE REVIEW

**Comment by PKUFlyingPig** [comment]
I think maybe the better way is to add an English version for the readme.

**Comment by zxtanzxzx** [comment]
Sure, I can work on that. Can you suggest file name and where to put the file

**Comment by PKUFlyingPig** [comment]
You can add a file `README.en.md` in the root folder of the project and reference it in the current readme.

**Comment by PKUFlyingPig** [comment]
Sure, I will check the PR tomorrow.

**Pull request closed without merging**
